# Generated by Django 5.2.4 on 2025-12-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
