# Generated by Django 5.2.4 on 2025-12-23 16:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0003_favorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='helpful_users',
            field=models.ManyToManyField(blank=True, related_name='helpful_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
